#启动端口
server:
  port: 12456
#资源配置
spring:  
  profiles:  
    active: dev  
  
  


    
---    
spring:  
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.20:3306/yazhai_job?useUnicode=true&characterEncoding=UTF8
    username: ishuaji
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver    



